services:
  - type: web
    name: global-climate-dashboard
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r dashboard/requirements.txt
    startCommand: gunicorn --chdir dashboard app:server --bind 0.0.0.0:$PORT --timeout 120
